### ISSUE TITLE
install.sh references non-existant image on quay.io

### ISSUE THREAD

**Issue by cprivite** [purestorage/helm-charts#105]
The install.sh script for the operator-csi-plugin references the following:
IMAGE=quay.io/purestorage/pso-operator:v5.0.0 

However, the highest tagged image on quay.io/purestorage is:
quay.io/purestorage/pso-operator:v0.0.5

Because of this, the operator-csi-plugin installer does not succeed. The pod it creates is forever stuck on trying to download an image that doesn't exist.

**Comment by pure-yesmat** [comment]
Hi @cprivite,

We haven't officially released our CSI drivers yet. The images that contain the CSI drivers are not pushed yet. This is just setting up the ground work for our release (hopefully soon).

Thanks,
Youssef

**Comment by cprivite** [comment]
Ok, would be nice if that was somehow made clear on the github page.

**Comment by cprivite** [comment]
@pure-yesmat with the pure-csi commit on Tuesday, does that mean the CSI drivers are now released officially?

**Comment by sdodsley** [comment]
Yes. And we are cleaning up the docs as well.

**Comment by sdodsley** [comment]
That image is now in quay.io
