### ISSUE TITLE
Clarify the usage of flasharray.preemptAttachments

### ISSUE THREAD

**Issue by javefang** [purestorage/helm-charts#112]
Hi! Could you add some more explanation on what this option do? Thanks!

**Comment by sdodsley** [comment]
I'm sure an engineer will jump in here and correct my definition, but this is effectively the same as storage fencing.
Depending on the version of kubernetes, stateful sets don't handle restarting containers very well. in an ideal world, the volume would be first unmounting on the failing node, then remounted on the new node where the pod is starting up but owing to the nature of the failure mode (e.g. network partition), or timing of the infrastructure, kubernetes may end up **mounting the same RWO volume simultaneously on different nodes**.
PSO prevents that with a builtin data RWO mount guarantee using the preemption/fencing feature. We will first do an array-side disconnect of the volume before connecting it to the new node. this way even though k8s can cause itself problems, we will ensure that a block volume is only mounted once at any given point in time. 
You can turn this feature off by setting this parameter to `false`, but TBH not sure why you would ever want to do that.

**Comment by javefang** [comment]
thank you @sdodsley for the explanation, this is my expectation. we connect to flasharray with ISCSI, and sometimes we are seeing multipathd and other IO errors which looks like a volume has been force disconnected before kubelet can unmount the filesystem properly. not sure if this is related.

**Comment by taherv** [comment]
@sdodsley explanation is spot on.
Just two things to add :
a. If you are running k8s 1.13 or later, you should not need this.
b. When preemption is turned off, a mount with an existing connection from a different node will FAIL. this can take pod restarts to take longer, and might impact uptime of the application. We favor data integrity over application availability.

**Comment by javefang** [comment]
Thank you @taherv, super clear!
