### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by chrisadkin** [purestorage/helm-charts#118]
Apparently there has been an internal discussion and we believe that the CSI driver supports Ubuntu 18.04, if this is genuinely the case, can the READEME be updated to reflect this.

**Comment by sdodsley** [comment]
Show me the CI results for Ubuntu 18.04 are passing and we can certainly add that OS to the READMe

**Comment by chrisadkin** [comment]
In that case, as you were.

**Comment by sdodsley** [comment]
Docs updated to reflect Ubuntu 18.04 is now supported
