### ISSUE TITLE
support for zones in a cluster ?

### ISSUE THREAD

**Issue by menardorama** [purestorage/helm-charts#126]
Hi,

Is it possible (using flexvolume or csi) to segregate the cluster so that the pure storage class can only be used on specific nodes ?

I am implementing a flasharray san on kubernetes and wanted to connect it using FC.
One of our big GPU server don't support FC cards and I don't want to use ISCSI.

So my question is as I can see in the chart that there is some nodeselector parameter; is defining a node selector will restrict mount to the selected nodes ?

Thanks a lot.

**Comment by sdodsley** [comment]
By using the nodeselector this will control the nodes the driver can be installed on. You will also need to explain to kubernetes that to shouldn't try to create a pod that needs a PSO based PV not to start on one of the nodes without the driver...
