### ISSUE TITLE
These K8s charts are still using deprecated apiVersions

### ISSUE THREAD

**Issue by asfdtodd** [purestorage/helm-charts#142]
pso deployments are broken:

{"level":"error","ts":1575570508.7013617,"logger":"helm.controller","msg":"Release failed","namespace":"pso-operator","name":"psoplugin-operator","apiVersion":"purestorage.com/v1","kind":"PSOPlugin","release":"psoplugin-operator-5igmuk6pvf7od89wp3m0z75rr","error":"failed to install release: validation failed: [unable to recognize \"\": no matches for kind \"DaemonSet\" in version \"extensions/v1beta1\", unable to recognize \"\": no matches for kind \"Deployment\" in version \"apps/v1beta1\"]",

helm chart deployments are broken for the same reason.

It's been almost three months since the release of K8s 1.16 and I figured you guys would be on it by now.
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

**Comment by taherv** [comment]
Are you blocked by this ? If so, can I interest you to submit a patch ? :)

**Comment by asfdtodd** [comment]
No, I'm not blocked. I forked it and updated the manifests myself and I'm using my own repo for now. I'm not familiar enough writing helm charts to attempt a patch and make a pull request. The maintainer should be able to knock this out no problem.

**Comment by taherv** [comment]
Cool !

I would still encourage you to submit your patch, we can throw it at our internal CI system. Saves us having to redo some of the work you did.

Your choice.
We'll try to get to this sooner than later.

**Comment by 2vcps** [comment]
Also, the CSI Driver helm chart does not use the older API versions. Have you tried moving to CSI or is there something in the FlexDriver you need that is not in CSI yet?

**Comment by asfdtodd** [comment]
> Also, the CSI Driver helm chart does not use the older API versions. Have you tried moving to CSI or is there something in the FlexDriver you need that is not in CSI yet?

According to the instructions there's no migration path from the flexdriver to CSI.

**Comment by trevormeiss** [comment]
Fixed by https://github.com/purestorage/helm-charts/pull/151
