### ISSUE TITLE
Possible to have StorageClass support allowVolumeExpansion

### ISSUE THREAD

**Issue by kengibous** [purestorage/helm-charts#154]
If a provisioned PVC is running low on space, what is the recommended approach to expanding?  The current StorageClass does not specify allowVolumeExpansion: true

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims

Would this be a possibility?

Thank you!

**Comment by sdodsley** [comment]
Volume Expansion is being added in the next quarter for PSO.

**Comment by kengibous** [comment]
@sdodsley  Thank you!
