### ISSUE TITLE
node-driver-registrar preStop hook: stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by javefang** [purestorage/helm-charts#178]
Issue:

pure-csi (daemonset) pod failed to stop due to preStop hook exec failure. (stat /bin/sh: no such file or directory).

Cause:

The preStop hook is trying to run on image "quay.io/k8scsi/csi-node-driver-registrar:v1.1.0"
https://github.com/purestorage/helm-charts/blob/5.0.7/pure-csi/templates/node.yaml#L84-L90
which stopped including /bin/sh since version v1.1.0.

How to reproduce:

1. Install the pure-csi driver 5.0.6
2. Wait for pure-csi daemonset pod to start
3. Delete one of the pure-csi pod
4. "k describe pod pure-csi-<id>"

OR

```
dockr run --rm -ti --entrypoint /bin/sh quay.io/k8scsi/csi-node-driver-registrar:v1.1.0 
```

Environment:

OS: Centos 7
Kubernetes: v1.14.5
Pure-csi: 5.0.6 (also a problem for 5.0.7)

**Comment by sdodsley** [comment]
@javefang after trawling through some repos and readme's it looks like the `preStop` hook is actually redundant. 
All we should need to do is remove the hook. Do you agree with this assessment?

**Comment by javefang** [comment]
Hi @sdodsley , thanks for the swift reply! Looking at https://github.com/kubernetes-csi/node-driver-registrar/issues/21, it feels like the maintainer knows about this and is thinking of replacing the preStop hook with a SIGTERM handler. But the issue is still open.

It is probably ok to remove the preStop hook here as it is: 1) not serving the purpose 2) causing pod stop failure. Do you know if the driver can restart fine if the two paths/files that the hook was trying to delete already exist?

**Comment by sdodsley** [comment]
I'll check this out and get back to you.

**Comment by sdodsley** [comment]
Reolved
