### ISSUE TITLE
k8s provisioner support for PURE_ISCSI_ALLOWED_CIDRS

### ISSUE THREAD

**Issue by GeoffCraig** [purestorage/helm-charts#226]
The k8s provisioner does not support setting the PURE_ISCSI_ALLOWED_CIDRS option.

**Comment by sdodsley** [comment]
Can you provide more details on your issue?

PURE_ISCSI_ALLOWED_CIDRS is definitely allowed in PSO and has been around for a long time.

Use `iSCSIAllowedCIDR` in the `flasharray` section of the `values.yaml` file
