### ISSUE TITLE
create a git repo for operator

### ISSUE THREAD

**Issue by mscbpi** [purestorage/helm-charts#227]
- Please clarify your position/best practice concerning the depreciation of helm charts - now that it uses helm 3 w/o Tiller

It seems still easier to deploy with helm.

- Operator deployment is part of the "helm-charts" repo which is quite confusing

**Comment by sdodsley** [comment]
Helm Charts using Helm 3 is the preferred installation method. The operator is only there for earlier versions of OpenShift which do not support Helm3.

**Comment by mscbpi** [comment]
Thank you!

My 2 cents:

Then it is quite confusing that you mention a [Migrating from Helm to Operator](https://github.com/purestorage/helm-charts/blob/master/operator-csi-plugin/README.md#migrating-from-helm-to-operator) section in the doc.

The presence of the operator mixed with helm-charts in the same repo named helm-charts is also confusing as mentioned above (not to mention Pure Storage Orchestrator PSO vs. Pure Storage Operator PSO may also lead to some unclarity).

[This article](https://blog.purestorage.com/pso-operator-lives/) also presents operator as a better alternative to helm (2), it's only a deduction that helm3 is eventually preferred,

**Comment by sdodsley** [comment]
I agree that section is confusing. We are revamping our docs and that that section is scheduled to be removed.

The blog post is old and definitely refers to Helm2. Helm3 is much more user friendly and with Red Hat now setting Helm as GA within OpenShift it largely spells the end of our operator installation method.

**Comment by sdodsley** [comment]
We are not maintaining the Operator for PSO. Helm3 is a fully supported GA installation method for OpenShift from 4.4.
