### ISSUE TITLE
Volume metrics in pure-csi

### ISSUE THREAD

**Issue by StuartWhelan** [purestorage/helm-charts#251]
I don't seem to be able to find any metrics on the PVC's that are attached to pure storage.

Is the pure-csi exposing metrics like kubelet_volume_stats_available_bytes?

**Comment by sdodsley** [comment]
Volumes metrics are only enabled in PSO v6.x which uses a different Helm chart - https://github.com/purestorage/pso-csi

**Comment by StuartWhelan** [comment]
I am not using PSO, I am not using operator. Are there no metrics for non-pos/generic k8 instances using pure-csi?

**Comment by dnix101** [comment]
@StuartWhelan All versions and editions are called PSO. If you are using pure-csi, you are currently using the CSI based version of PSO 5 that is installed using a Helm chart. This version has moved to PSO 6, which is also CSI based and installed using Helm. You can find PSO 6 on the repo mentioned by @sdodsley above.
