### ISSUE TITLE
Clarification on the future of the pure-csi helm chart

### ISSUE THREAD

**Issue by StuartWhelan** [purestorage/helm-charts#252]
In the header for the pure-csi helm chart there is a message:

_Feature Frozen: Pure Service Orchestrator 5.x is in feature freeze_

What does this mean for the non operator parts of the helm-charts repo, and how does it apply to the pure-csi chart?

**Comment by sdodsley** [comment]
PSO 5.x will have no further development applied to it. 

All new features and functionality are provided in PSO v6.x which uses a different Helm chart - https://github.com/purestorage/pso-csi.

This also applies to the operator. The operator is not supported with PSO v6.0 as all versions of OpenShift that support PSO v6 also fully support Helm3 as a GA installation method.

**Comment by StuartWhelan** [comment]
Sorry, I dont think I explained my question well.

What does this mean for the non operator parts of the helm-charts repo? 

I am not using PSO. I am using pure-csi, which is in the same repo, but does not use operator.

 What does the PSO feature freeze mean for the part of this repo that are not PSO specific?

**Comment by sdodsley** [comment]
PSO stands for Pure Service **Orchestrator**. It is not an operator, it is the customer facing name of the helm chart you see as pure-csi.

The helm chart pure-csi has been frozen and you should look to move to the pso-csi helm chart.
