### ISSUE TITLE
Upgrade from 2.0.1 to 2.1.0 fails

### ISSUE THREAD

**Issue by sdodsley** [purestorage/helm-charts#35]
When running the documented  process for the plugin using Helm, the upgrade fails:

```# helm upgrade pure-storage-driver pure/pure-k8s-plugin -f values.yaml --version 2.1.0 --recreate-pods```

Error: UPGRADE FAILED: DaemonSet.apps "pure-flex" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"generator":"helm", "release":"pure-storage-driver", "app":"pure-flex", "chart":"pure-k8s-plugin", "date":"2018-07-31"}: `selector` does not match template `labels` && Deployment.apps "pure-provisioner" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"release":"pure-storage-driver", "app":"pure-provisioner", "chart":"pure-k8s-plugin", "date":"2018-07-31", "generator":"helm"}: `selector` does not match template `labels`

**Comment by patrick-east** [comment]
Fix for this is in #37
