### ISSUE TITLE
Only create specified storage classes.

### ISSUE THREAD

**Issue by gregsidelinger** [purestorage/helm-charts#70]
Provide a way to enable/disable the three different storage classes.  For example I'm not setting up pure-file however the helm chart assumes I am and creates a storage class for it.

**Comment by taherv** [comment]
Hi Greg,
You never know when you might deploy a FlashBlade in your environment. Bad joke, I know, moving on ....

This might impact the usability aspect of the plugin, in a few ways
a. An extra knob on install to choose which storage classes are needed
b. Some way of going back and add the missing storage classes, if one does changes their fleet to need one.

You can always delete any of the builtin storage classes after install, if you think (b) will never happen to you. BTW, the "pure" storage class is provided for compatibility only. Feel free to delete that as well, and use pure-block for FlashArray.

**Comment by gregsidelinger** [comment]
I do not agree with having to bust out kubectl to cleanup the work a helm chart did.  Also extra knobs should not matter as long as they have good defaults.

I worked out an update to the chart this morning that provides backwards compatibility with existing settings but will allow each storageclass to be managed own it's own going forward.

**Comment by sdodsley** [comment]
This is no longer required due to latest updates and additional SC documentation
