### ISSUE TITLE
Storing api token in Secret instead of ConfigMap

### ISSUE THREAD

**Issue by javefang** [purestorage/helm-charts#72]
The `.Values.arrays` contains both non-sensitive data like management endpoint and also sensitive data like api token. Ideally credentials like api token should be stored as Secret instead of ConfigMap.

**Comment by taherv** [comment]
I agree, api tokens need to be secured.

Would this (https://developer.epages.com/blog/tech-stories/kubernetes-deployments-with-helm-secrets/) be a possible solution ?

@javefang suggestions are welcome !

**Comment by sdodsley** [comment]
@javefang are you saying you just want the API token to be in a secret, but still visible in the `values.yaml` file, or do you want to obfuscate in the YAML as well?

**Comment by javefang** [comment]
@taherv @sdodaley, I think for the scope of this chart, just moving the api token from ConfigMap to Secret will suffice. 

How to obfuscate the value from the values.yaml file can be left to user to solve. (E.g. helm secrets looks good)

**Comment by javefang** [comment]
I've submitted a PR as a potential solution for review :)
