### ISSUE TITLE
flexPath moved in values.yaml Can Break Upgrade Past 2.2.1

### ISSUE THREAD

**Issue by kdanthony** [purestorage/helm-charts#81]
The flexPath parameter was moved out from under orchestrator/k8s to the base of the yaml in [9871d64](https://github.com/purestorage/helm-charts/commit/9871d644fc9660e671870fbe5cf6e0320dd526d1#diff-67bb1c0c7602691fbf9fff7333c870ea) which causes upgrades past 2.2.1 to look successful but then not be able to actually mount the filesystems due to the volume plugin being installed incorrectly. Might want to note in the release notes that the values.yaml will have to be updated to work around this.

**Comment by sdodsley** [comment]
The recommendation is that when upgrading you should also grab the associated values.yaml for the version you are moving to. This will stop this happening.
We will certainly look to add something in the release notes.

**Comment by dinathom** [comment]
I have updated the Release Notes to indicate this.

**Comment by dinathom** [comment]
Fixed in latest chart
