### ISSUE TITLE
minimum Kubernetes version information

### ISSUE THREAD

**Issue by chrisadkin** [purestorage/helm-charts#96]
Can you please state in the README whether or not there is a minimum version of Kubernetes that PSO will work with.

**Comment by trevormeiss** [comment]
It is stated in the [pure-k8s-plugin README](https://github.com/purestorage/helm-charts/blob/master/pure-k8s-plugin/README.md#environments-supported) and the [operator README](https://github.com/purestorage/helm-charts/tree/master/operator#prerequisites). We can do a better job of linking to these READMEs from the top-level README.

**Comment by chrisadkin** [comment]
If you could do that, that would be most useful.

**Comment by inge4pres** [comment]
Hi there, if you are amending documentation please also fix the information on CSI status for Kubernetes versions.
https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/
CSI was alpha in 1.9 and beta in 1.10, now stable since 1.13.
Section https://github.com/purestorage/helm-charts/tree/master/pure-csi-plugin#additional-configuration-for-k8s-113 reports incorrect information

**Comment by sdodsley** [comment]
This is not what the document we link to, ie. https://kubernetes-csi.github.io/docs/csi-driver-object.html, says. The exact wording from that CSI documentation is:
Kubernetes 1.12 - 1.13: Alpha
Kubernetes 1.14: Beta
I do love a little conflict in the documentation, especially when both cited are each supposed to be 'sources of truth', although I do feel a blog is a little less 'truth' that the GitHub documentation for the actual driver. The joys of Open Source.

**Comment by inge4pres** [comment]
Sorry, my bad I misread the documentation here: CSIDriver is effectively alpha/beta as specified... while the whole CSI interface is instead as documented in the link I posted.
Sorry for the noise 😄

**Comment by sdodsley** [comment]
This has been resolved and the READMEs now cover minimum versions of software required
