### ISSUE TITLE
Support setting export rules on flashblade

### ISSUE THREAD

**Issue by justinrush** [purestorage/helm-charts#98]
The orchestrator creates the volume with a blank *.*.*.* (rw,no_root_squash) on the volume.  Would be good if we could limit this to our k8s subnets.

**Comment by taherv** [comment]
Could you please elaborate ?

**Comment by justinrush** [comment]
I would like to have the pure container that creates the flashblade volume, and the sets the NFS export, also put an access list on the volume.  Right now, it allows anyone, anywhere, to mount the share read/write.  For example, it would be great if I could provide these values overrides for the helm chart:
`flashblade:
  snapshotDirectoryEnabled: "false"
  exports:
    ipRange: "192.168.74.0/24"
    options: "rw, no_root_squash"`

**Comment by taherv** [comment]
Got it.
Thanks !

**Comment by sdodsley** [comment]
@justinrush Great comments and I support this request, however as this is actually a feature request and not a bug we will need you to reach out to your local Pure SE and tell them what you want. Also, get them to directly contact me and @taherv so we can help the process along.

**Comment by sdodsley** [comment]
@justinrush This has been added to the PSO roadmap and should be available later this year.

**Comment by mscbpi** [comment]
We made the exact same request to our SE today. Thanks.

**Comment by sdodsley** [comment]
This feature is included in PSO v6.0.0 which will ship in the next month
